improve output and return values

diff --git a/.github/actions/set/variable/action.yaml b/.github/actions/set/variable/action.yaml
--- a/.github/actions/set/variable/action.yaml
+++ b/.github/actions/set/variable/action.yaml
@@ -41,6 +41,7 @@ runs:
         status=$(echo "$output" | jq '( .status // empty )')
         # status is "" or HTTP error code
         if [ -n "$status" ] ; then
-          echo "::setFailed ::status from set variable call is $status"
+          echo "::error ::status from set variable call is $status"
+          exit 1
         fi
         echo "Set vars.${VARIABLE}=${VALUE} in $REPO"
