fix syntax

diff --git a/.github/actions/get/vars2/action.yaml b/.github/actions/get/vars2/action.yaml
--- a/.github/actions/get/vars2/action.yaml
+++ b/.github/actions/get/vars2/action.yaml
@@ -51,8 +51,9 @@ runs:
             echo "$key=$val" >> $GITHUB_OUTPUT
           else
             if [[ "$key" != "private_access_token" && "$key" != "terraform_private_key" ]]; then # TODO: improve
-            echo "ERROR: $key is empty. exiting."
-            exit 1
+              echo "ERROR: $key is empty. exiting."
+              exit 1
+            fi
           fi
         done
 
