try get-vars with yaml param

diff --git a/.github/actions/get/vars2/action.yaml b/.github/actions/get/vars2/action.yaml
--- a/.github/actions/get/vars2/action.yaml
+++ b/.github/actions/get/vars2/action.yaml
@@ -1,30 +1,7 @@
 name: Get vars
 
 inputs:
-  access_domain:
-    required: true
-  access_role:
-    required: true
-    default: AdministratorAccess
-  backend_account:
-    required: true
-  backend_region:
-    required: true
-    default: eu-central-1
-  deployment_account:
-    required: true
-  deployment_region:
-    required: true
-    default: eu-central-1
-  environment:
-    required: true
-  oidc_principal:
-    required: true
-  private_access_token:
-    required: true
-  terraform_app_id:
-    required: true
-  terraform_private_key:
+  yaml:
     required: true
 
 outputs:
@@ -62,6 +39,7 @@ runs:
       shell: bash
       run: |
         # get/vars
+
         function check() {
           key=$1
           val=$2
@@ -73,11 +51,18 @@ runs:
             exit 1
           fi
         }
-        check access_domain    "${{ inputs.access_domain }}"
-        check access_role      "${{ inputs.access_role }}"
-        check backend_account  "${{ inputs.backend_account }}"
-        check backend_region   "${{ inputs.backend_region }}"
-        check oidc_principal   "${{ inputs.oidc_principal }}"
+
+        for line in ${{ inputs.yaml }} ; do
+          key=${line%%:.*}
+          val=§(line##.*:)
+          if [ -n "$val" ] ; then
+            # echo "$key=$val" | tee -a $GITHUB_OUTPUT
+            echo "$key=$val" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: $key is empty. exiting."
+            exit 1
+          fi
+        done
 
     - name: Get Token
       id: get-token
